'use client';
import {useEffect,useState} from 'react';
import Layout from '@/components/Layout';
import AuthGuard from '@/components/AuthGuard';
import {api} from '@/lib/api';

type U={id:string;employee_code:string;full_name:string;username:string;email:string;phone?:string;company_id:string;company_name:string;department_id?:string;department_name?:string;role:string;status:string;notes?:string};
type C={id:string;name:string}; type D={id:string;company_id:string;name:string};
type Form={employee_code:string;username:string;full_name:string;email:string;phone:string;company_id:string;department_id:string;role:string;notes:string;password:string};
const empty:Form={employee_code:'',username:'',full_name:'',email:'',phone:'',company_id:'',department_id:'',role:'USER',notes:'',password:''};

export default function Users(){
 const [items,setItems]=useState<U[]>([]),[companies,setCompanies]=useState<C[]>([]),[departments,setDepartments]=useState<D[]>([]);const [q,setQ]=useState(''),[status,setStatus]=useState(''),[companyId,setCompanyId]=useState(''),[departmentId,setDepartmentId]=useState('');const [form,setForm]=useState<Form>(empty);const [editing,setEditing]=useState<string|null>(null);const [error,setError]=useState('');
 const load=async()=>{try{const qs=new URLSearchParams({q,status,company_id:companyId,department_id:departmentId});const x=await api<{data:U[]}>(`/users?${qs}`);setItems(x.data)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{Promise.all([api<{data:C[]}>('/companies'),api<{data:U[]}>('/users?status=ACTIVE')]).then(([c])=>setCompanies(c.data)).catch(e=>setError(e.message));load()},[]);
 useEffect(()=>{if(companyId)api<{data:D[]}>(`/departments?company_id=${encodeURIComponent(companyId)}`).then(x=>setDepartments(x.data)).catch(e=>setError(e.message));else setDepartments([])},[companyId]);
 const submit=async()=>{setError('');try{if(editing){const body={...form,department_id:form.department_id||null};delete (body as any).password;await api(`/users/${editing}`,{method:'PUT',body:JSON.stringify(body)})}else{if(!form.password)return setError('Nhân viên mới bắt buộc có mật khẩu ban đầu.');await api('/users',{method:'POST',body:JSON.stringify({...form,department_id:form.department_id||null})})}setForm(empty);setEditing(null);await load()}catch(e){setError((e as Error).message)}};
 const beginEdit=(u:U)=>{setEditing(u.id);setForm({employee_code:u.employee_code,username:u.username,full_name:u.full_name,email:u.email,phone:u.phone||'',company_id:u.company_id,department_id:u.department_id||'',role:u.role,notes:u.notes||'',password:''})};
 const remove=async(id:string)=>{if(!confirm('Xóa mềm nhân viên này?'))return;try{await api(`/users/${id}`,{method:'DELETE'});await load()}catch(e){setError((e as Error).message)}};
 const resign=async(u:U)=>{const replacement=prompt('Nhập username của nhân viên thay thế (để trống nếu chưa có):','');if(replacement===null)return;const target=items.find(x=>x.username===replacement&&x.id!==u.id);if(replacement&&!target)return setError('Không tìm thấy nhân viên ACTIVE trong danh sách lọc hiện tại. Hãy dùng username chính xác hoặc để trống.');try{await api(`/users/${u.id}/resign`,{method:'POST',body:JSON.stringify({replacement_user_id:target?.id||null})});await load()}catch(e){setError((e as Error).message)}};
 return <AuthGuard><Layout><div className="topbar"><div><div className="title">Nhân viên</div><div className="subtitle">Quản lý nhân sự, tài khoản và vòng đời truy cập</div></div></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="card"><div className="toolbar"><input className="input" placeholder="Tìm tên, mã NV, username, email..." value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option value="ACTIVE">ACTIVE</option><option value="RESIGNED">RESIGNED</option><option value="DISABLED">DISABLED</option></select><select className="select" value={companyId} onChange={e=>{setCompanyId(e.target.value);setDepartmentId('');setForm(f=>({...f,company_id:e.target.value,department_id:''}))}}><option value="">Tất cả công ty</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="select" value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Tất cả phòng ban</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="button primary" onClick={load}>Tìm kiếm</button></div></div>
 <div className="card"><div className="toolbar"><input className="input" placeholder="Mã NV" value={form.employee_code} onChange={e=>setForm({...form,employee_code:e.target.value})}/><input className="input" placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input className="input" placeholder="Họ tên" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input className="input" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="Số điện thoại" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><select className="select" value={form.company_id} onChange={e=>{setForm({...form,company_id:e.target.value,department_id:''});}}><option value="">Công ty</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="select" value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">Phòng ban</option>{departments.filter(d=>!form.company_id||d.company_id===form.company_id).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select className="select" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="USER">USER</option><option value="ADMIN">ADMIN</option><option value="SUPER_ADMIN">SUPER_ADMIN</option><option value="AUDITOR">AUDITOR</option></select>{!editing&&<input className="input" type="password" placeholder="Mật khẩu ban đầu" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>}<input className="input" placeholder="Ghi chú" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="button primary" onClick={submit}>{editing?'Lưu nhân viên':'Thêm nhân viên'}</button>{editing&&<button className="button" onClick={()=>{setEditing(null);setForm(empty)}}>Hủy</button>}</div></div>
 <div className="table-wrap"><table className="table"><thead><tr><th>Mã NV</th><th>Họ tên</th><th>Username</th><th>Công ty</th><th>Phòng ban</th><th>Role</th><th>Status</th><th>Thao tác</th></tr></thead><tbody>{items.map(u=><tr key={u.id}><td>{u.employee_code}</td><td>{u.full_name}</td><td>{u.username}</td><td>{u.company_name}</td><td>{u.department_name||'—'}</td><td>{u.role}</td><td><span className={`badge ${u.status==='ACTIVE'?'green':u.status==='RESIGNED'?'red':'blue'}`}>{u.status}</span></td><td><button className="button" onClick={()=>beginEdit(u)}>Sửa</button>{' '} {u.status==='ACTIVE'&&<button className="button" onClick={()=>resign(u)}>Nghỉ việc</button>} {' '}<button className="button danger" onClick={()=>remove(u.id)}>Xóa</button></td></tr>)}</tbody></table>{!items.length&&<div className="empty">Không có nhân viên phù hợp.</div>}</div></Layout></AuthGuard>
}
