'use client';
import {useEffect,useState} from 'react';
import Layout from '@/components/Layout';import AuthGuard from '@/components/AuthGuard';import {api} from '@/lib/api';

type C={id:string;code:string;name:string;description:string;status:string};
const empty={code:'',name:'',description:''};
export default function Companies(){
 const [items,setItems]=useState<C[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[q,setQ]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const x=await api<{data:C[]}>(`/companies?q=${encodeURIComponent(q)}`);setItems(x.data)}catch(e){setError((e as Error).message)}};useEffect(()=>{load()},[]);
 const submit=async()=>{setError('');try{if(!form.code.trim()||!form.name.trim())return setError('Mã và tên công ty là bắt buộc.');const body=JSON.stringify(form);if(editing)await api(`/companies/${editing}`,{method:'PUT',body});else await api('/companies',{method:'POST',body});setForm(empty);setEditing(null);await load()}catch(e){setError((e as Error).message)}};
 const remove=async(id:string)=>{if(!confirm('Xóa mềm công ty này? Dữ liệu lịch sử vẫn được giữ lại.'))return;try{await api(`/companies/${id}`,{method:'DELETE'});await load()}catch(e){setError((e as Error).message)}};
 return <AuthGuard><Layout><div className="topbar"><div><div className="title">Công ty</div><div className="subtitle">Quản lý tenant và dữ liệu tổ chức</div></div></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="card"><div className="toolbar"><input className="input" placeholder="Mã công ty" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input className="input" placeholder="Tên công ty" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Mô tả" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="button primary" onClick={submit}>{editing?'Lưu thay đổi':'Thêm công ty'}</button>{editing&&<button className="button" onClick={()=>{setEditing(null);setForm(empty)}}>Hủy</button>}</div></div><div className="toolbar"><input className="input" placeholder="Tìm công ty..." value={q} onChange={e=>setQ(e.target.value)}/><button className="button" onClick={load}>Tìm kiếm</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Tên</th><th>Mô tả</th><th>Status</th><th>Thao tác</th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td>{c.code}</td><td>{c.name}</td><td>{c.description}</td><td><span className={`badge ${c.status==='ACTIVE'?'green':'red'}`}>{c.status}</span></td><td><button className="button" onClick={()=>{setEditing(c.id);setForm({code:c.code,name:c.name,description:c.description})}}>Sửa</button>{' '}<button className="button danger" onClick={()=>remove(c.id)}>Xóa</button></td></tr>)}</tbody></table>{!items.length&&<div className="empty">Chưa có công ty.</div>}</div></Layout></AuthGuard>
}
