'use client';
import {useEffect,useState} from 'react';
import Layout from '@/components/Layout';import AuthGuard from '@/components/AuthGuard';import {api} from '@/lib/api';
type U={id:string;employee_code:string;full_name:string;company_name:string;resigned_at?:string;replacement_user_id?:string;notes?:string};
type A={id:string;full_name:string;username:string};
export default function Resigned(){const[items,setItems]=useState<U[]>([]),[allUsers,setAllUsers]=useState<A[]>([]),[q,setQ]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const x=await api<{data:U[]}>(`/users?status=RESIGNED&q=${encodeURIComponent(q)}`);setItems(x.data)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{Promise.all([api<{data:U[]}>('/users?status=RESIGNED'),api<{data:U[]}>('/users')]).then(([r,a])=>{setItems(r.data);setAllUsers(a.data.map(u=>({id:u.id,full_name:u.full_name,username:u.username})))}).catch(e=>setError(e.message))},[]);
 return <AuthGuard><Layout><div className="topbar"><div><div className="title">Nhân viên nghỉ việc</div><div className="subtitle">Lưu lịch sử nghỉ việc, ghi chú và người thay thế</div></div></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="toolbar"><input className="input" placeholder="Tìm nhân viên..." value={q} onChange={e=>setQ(e.target.value)}/><button className="button" onClick={load}>Tìm kiếm</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Mã NV</th><th>Họ tên</th><th>Công ty</th><th>Ngày nghỉ</th><th>Người thay thế</th><th>Ghi chú</th></tr></thead><tbody>{items.map(u=>{const repl=allUsers.find(x=>x.id===u.replacement_user_id);return <tr key={u.id}><td>{u.employee_code}</td><td>{u.full_name}</td><td>{u.company_name}</td><td>{u.resigned_at?new Date(u.resigned_at).toLocaleDateString('vi-VN'):'—'}</td><td>{repl?`${repl.full_name} (${repl.username})`:u.replacement_user_id||'Chưa chỉ định'}</td><td>{u.notes||'—'}</td></tr>})}</tbody></table>{!items.length&&<div className="empty">Chưa có nhân viên nghỉ việc.</div>}</div></Layout></AuthGuard>}
