'use client';
import {useEffect,useState} from 'react';
import Layout from '@/components/Layout';import AuthGuard from '@/components/AuthGuard';import {api} from '@/lib/api';
type P={id:string;user_id:string;project_id:string;level:string;user_name:string;project_name:string;resource_name?:string};type U={id:string;full_name:string;username:string;status:string};type Pr={id:string;name:string;code:string;company_name:string};
export default function Permissions(){const [items,setItems]=useState<P[]>([]),[users,setUsers]=useState<U[]>([]),[projects,setProjects]=useState<Pr[]>([]),[form,setForm]=useState({user_id:'',project_id:'',level:'READ'}),[filterUser,setFilterUser]=useState(''),[filterProject,setFilterProject]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const qs=new URLSearchParams({user_id:filterUser,project_id:filterProject});const x=await api<{data:P[]}>(`/permissions?${qs}`);setItems(x.data)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{Promise.all([api<{data:U[]}>('/users?status=ACTIVE'),api<{data:Pr[]}>('/projects')]).then(([u,p])=>{setUsers(u.data);setProjects(p.data)}).catch(e=>setError(e.message));load()},[]);
 const save=async()=>{setError('');try{if(!form.user_id||!form.project_id)return setError('Vui lòng chọn nhân viên và dự án.');await api('/permissions',{method:'POST',body:JSON.stringify({...form,resource_id:null})});await load()}catch(e){setError((e as Error).message)}};
 return <AuthGuard><Layout><div className="topbar"><div><div className="title">Phân quyền</div><div className="subtitle">Quản lý quyền truy cập theo nhân viên và dự án</div></div></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="card"><h3 style={{marginTop:0}}>Cấp / cập nhật quyền</h3><div className="toolbar"><select className="select" value={form.user_id} onChange={e=>setForm({...form,user_id:e.target.value})}><option value="">Chọn nhân viên</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name} · {u.username}</option>)}</select><select className="select" value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Chọn dự án</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name} · {p.company_name}</option>)}</select><select className="select" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option value="NONE">X · Không truy cập</option><option value="READ">R · Chỉ xem</option><option value="WRITE">W · Chỉnh sửa</option></select><button className="button primary" onClick={save}>Lưu quyền</button></div><div className="subtitle">Quyền project-level ở MVP này. Resource/folder-level sẽ nối vào danh mục thư mục ở bước tiếp theo.</div></div><div className="card"><h3 style={{marginTop:0}}>Bộ lọc</h3><div className="toolbar"><select className="select" value={filterUser} onChange={e=>setFilterUser(e.target.value)}><option value="">Tất cả nhân viên</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select><select className="select" value={filterProject} onChange={e=>setFilterProject(e.target.value)}><option value="">Tất cả dự án</option>{projects.map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select><button className="button" onClick={load}>Lọc</button></div></div><div className="table-wrap"><table className="table"><thead><tr><th>Nhân viên</th><th>Dự án</th><th>Resource</th><th>Permission</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.user_name}</td><td>{p.project_name}</td><td>{p.resource_name||'Toàn dự án'}</td><td><span className={`badge ${p.level==='WRITE'?'blue':p.level==='READ'?'green':'red'}`}>{p.level}</span></td></tr>)}</tbody></table>{!items.length&&<div className="empty">Chưa có quyền nào.</div>}</div></Layout></AuthGuard>}
