'use client';
import {useEffect,useState} from 'react';
import Layout from '@/components/Layout';import AuthGuard from '@/components/AuthGuard';import {api} from '@/lib/api';
type P={id:string;code:string;name:string;company_id:string;company_name:string;status:string;folder_path:string};type C={id:string;name:string};
const empty={company_id:'',code:'',name:'',folder_path:''};
export default function Projects(){const [items,setItems]=useState<P[]>([]),[companies,setCompanies]=useState<C[]>([]),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[q,setQ]=useState(''),[companyId,setCompanyId]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const x=await api<{data:P[]}>(`/projects?q=${encodeURIComponent(q)}&company_id=${encodeURIComponent(companyId)}`);setItems(x.data)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{api<{data:C[]}>('/companies').then(x=>setCompanies(x.data)).catch(e=>setError(e.message));load()},[]);
 const submit=async()=>{setError('');try{if(!form.company_id||!form.code.trim()||!form.name.trim())return setError('Công ty, mã dự án và tên dự án là bắt buộc.');const body=JSON.stringify({...form,status:'ACTIVE'});if(editing)await api(`/projects/${editing}`,{method:'PUT',body});else await api('/projects',{method:'POST',body});setForm(empty);setEditing(null);await load()}catch(e){setError((e as Error).message)}};
 const remove=async(id:string)=>{if(!confirm('Xóa mềm dự án này?'))return;try{await api(`/projects/${id}`,{method:'DELETE'});await load()}catch(e){setError((e as Error).message)}};
 return <AuthGuard><Layout><div className="topbar"><div><div className="title">Dự án</div><div className="subtitle">Dự án gắn với công ty và thư mục File Server</div></div></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<div className="card"><div className="toolbar"><select className="select" value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">Chọn công ty</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="input" placeholder="Mã dự án" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input className="input" placeholder="Tên dự án" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="\\server\projects\..." value={form.folder_path} onChange={e=>setForm({...form,folder_path:e.target.value})}/><button className="button primary" onClick={submit}>{editing?'Lưu thay đổi':'Thêm dự án'}</button>{editing&&<button className="button" onClick={()=>{setEditing(null);setForm(empty)}}>Hủy</button>}</div></div><div className="toolbar"><input className="input" placeholder="Tìm dự án..." value={q} onChange={e=>setQ(e.target.value)}/><select className="select" value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="">Tất cả công ty</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="button" onClick={load}>Tìm kiếm</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Dự án</th><th>Công ty</th><th>Folder</th><th>Status</th><th>Thao tác</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{p.company_name}</td><td>{p.folder_path||'—'}</td><td><span className="badge blue">{p.status}</span></td><td><button className="button" onClick={()=>{setEditing(p.id);setForm({company_id:p.company_id,code:p.code,name:p.name,folder_path:p.folder_path||''})}}>Sửa</button>{' '}<button className="button danger" onClick={()=>remove(p.id)}>Xóa</button></td></tr>)}</tbody></table>{!items.length&&<div className="empty">Chưa có dự án.</div>}</div></Layout></AuthGuard>}
